services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes: 
      - type: volume
        source: webserve-nginx
        target: /var/docker-volume

volumes:
  webserve-nginx: