name: Hello, World!
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: "install cpplint"
      run: pip install cpplint

    - name: "lint check"
      run: make lint
